//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESTAURANTES
    {
        public int ID { get; set; }
        public string placeID { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string the_geom_meter { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string fax { get; set; }
        public string zip { get; set; }
        public string alcohol { get; set; }
        public string smoking_area { get; set; }
        public string dress_code { get; set; }
        public string accessibility { get; set; }
        public string price { get; set; }
        public string url { get; set; }
        public string Rambience { get; set; }
        public string franchise { get; set; }
        public string area { get; set; }
        public string other_services { get; set; }
    }
}
