//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public string userID { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string smoker { get; set; }
        public string drink_level { get; set; }
        public string dress_preference { get; set; }
        public string ambience { get; set; }
        public string transport { get; set; }
        public string marital_status { get; set; }
        public string hijos { get; set; }
        public string birth_year { get; set; }
        public string interest { get; set; }
        public string personality { get; set; }
        public string religion { get; set; }
        public string activity { get; set; }
        public string color { get; set; }
        public string weight { get; set; }
        public string budget { get; set; }
        public string height { get; set; }
        public int ID { get; set; }
    }
}
