//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecommendationAppDBEntities : DbContext
    {
        public RecommendationAppDBEntities()
            : base("name=RecommendationAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caballito> Caballito { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<Caballodetroya> Caballodetroya { get; set; }
        public virtual DbSet<RESTAURANTES> RESTAURANTES { get; set; }
        public virtual DbSet<TIPO_COMIDA> TIPO_COMIDA { get; set; }
    }
}
